name: Docker Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}  # Folosește username-ul GitHub
        password: ${{ secrets.GHCR_PAT }}  # Folosește secretul CR_PAT creat anterior
        registry: ghcr.io  # Asigură-te că folosești GHCR

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}:latest .

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ github.repository }}:latest
